export const INGREDIENTS = [
  { title: "Spaghetti" },
  { title: "Ground Beef" },
  { title: "Tomato Sauce" },
  { title: "Onion" },
  { title: "Garlic" },
  { title: "Romaine Lettuce" },
  { title: "Grilled Chicken Breast" },
  { title: "Caesar Dressing" },
  { title: "Pizza Dough" },
  { title: "Tomatoes" },
  { title: "Bell Pepper" },
  { title: "Mushrooms" },
  { title: "Cheese (Mozzarella)" },
  { title: "Chocolate Chips" },
  { title: "Flour" },
  { title: "Butter" },
  { title: "Tomato Basil Soup" },
  { title: "Shrimp" },
  { title: "Taco Shells" },
  { title: "Arborio Rice" },
];
